### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by tfriedel** [HelenaELiu/FROST#1]
I'm eager to try it, but I noticed requirements.txt is missing, both for TF & PT.

**Comment by HelenaELiu** [comment]
Dear Mr. Friedel,

Thank you for your interest.

We've just added requirements.txt for TF under TF-FROST. For PT, the README
under PT-FROST has the installation instructions along with the
dependencies.

Have a wonderful day!

Best regards,
Helena Liu

**Comment by tfriedel** [comment]
Thanks Helena!

I installed the dependencies with Pip but ran into the problem that my GPUs were not used. This was mentioned in the [Fixmatch issues](https://github.com/google-research/fixmatch/issues/38).
The proposed solution was to use conda instead of pip, which worked for me. 

Here's the command that will install the dependencies into a conda environment:
```
conda install -c conda-forge -c Esri tensorflow-gpu==1.14 absl-py pillow-simd tqdm cython easydict scipy numpy easydict pillow-simd
```
