### ISSUE TITLE
The purpose of shadow

### ISSUE THREAD

**Issue by cccntu** [HelenaELiu/FROST#2]
Hi, I am using the Pytorch version. In the `ema.py`, there is a `self.shadow`, it seems to be used in `apply_shadow()` and in turn used in `evaluate()` and `sort_unlabeled()` in `frost.py`.

What's the purpose of shadow version of weights? It seems only use in inference.
Also what does the name `EMA` stands for? I am new to this area of research.

Thanks!

**Comment by tfriedel** [comment]
EMA stands for Exponential Moving Average. The shadow variable contains the moving average. For a more detailed explanation have a look [here](https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage).

**Comment by HelenaELiu** [comment]
Yes, that is correct. Thank you for answering the question!

**Comment by HelenaELiu** [comment]
I am closing this issue as the question has been answered.
